# Generated by Django 3.1.5 on 2021-02-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
