# Generated by Django 3.1.5 on 2021-02-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('longetivity', models.DurationField()),
                ('cost', models.PositiveSmallIntegerField()),
                ('calories', models.SmallIntegerField()),
                ('type', models.TextField(choices=[('FD', 'Food'), ('DV', 'Device'), ('HH', 'Household Object'), ('CL', 'Clothing'), ('MC', 'Misc')])),
            ],
        ),
    ]
